[default]

Integer_min = 0
Integer_max = 100

String_max = 50


# ---------------------------------------------------------------- EstadoMadurez

EstadoMadurez_nivel_min = 1
EstadoMadurez_nivel_max = 9

# -------------------------------------------------------------------------- TRL
TRL_min = 0
TRL_max = 2

TRL_activoReal_min = 0
TRL_activoReal_max = 1
TRL_contextoImpactoIncluido_min = 0
TRL_contextoImpactoIncluido_max = 2
TRL_esGeneradoPorIA_min = 0
TRL_esGeneradoPorIA_max = 1

# TRL_AuditoriaIA (trlAuditado:TRL, auditoriaIA:AuditoriaIA) - - - - - - - - - -
TRL_AuditoriaIA_min = 1
TRL_AuditoriaIA_max = 2

# -------------------------------------------------------------------------- CRL
CRL_min = 0
CRL_max = 2

CRL_metricaTraccion_min = 0
CRL_metricaTraccion_max = 2
CRL_validacionManualCompletada_min = 0
CRL_validacionManualCompletada_max = 2

# CRL_Validacion (crlDeValidacion:CRL, validaciones:Validacion)  - - - - - - - -
CRL_Validacion_min = 1
CRL_Validacion_max = 2

# -------------------------------------------------------------------------- IPL
IPL_min = 0
IPL_max = 2

IPL_beneficiariosEstimados_min = 0
IPL_beneficiariosEstimados_max = 1000
IPL_ejeImpacto_min = 0
IPL_ejeImpacto_max = 2
IPL_verificacionExterna_min = 0
IPL_verificacionExterna_max = 1

# IPL_MetricaClave (iplDeMetrica:IPL, metricasImpacto:MetricaClave)  - - - - - -
IPL_MetricaClave_min = 1
IPL_MetricaClave_max = 1

# IPL_Validacion (iplDeValidacion:IPL, validaciones:Validacion)  - - - - - - - -
IPL_Validacion_min = 1
IPL_Validacion_max = 1

# ---------------------------------------------------------------- PuntoDecision
PuntoDecision_min = 0
PuntoDecision_max = 2

PuntoDecision_etapaActual_min = 0
PuntoDecision_etapaActual_max = 5
PuntoDecision_idDecision_min = 0
PuntoDecision_idDecision_max = 2
PuntoDecision_trayectoriaSeleccionada_min = 0
PuntoDecision_trayectoriaSeleccionada_max = 2

# PuntoDecision_TRL (decisionTRL:PuntoDecision, trl:TRL) - - - - - - - - - - - -
PuntoDecision_TRL_min = 1
PuntoDecision_TRL_max = 2

# PuntoDecision_CRL (decisionCRL:PuntoDecision, crl:CRL) - - - - - - - - - - - -
PuntoDecision_CRL_min = 1
PuntoDecision_CRL_max = 2

# PuntoDecision_IPL (decisionIPL:PuntoDecision, ipl:IPL) - - - - - - - - - - - -
PuntoDecision_IPL_min = 1
PuntoDecision_IPL_max = 2

# PuntoDecision_MVPCero (decisionMVP:PuntoDecision, mvp_cero:MVP_Cero) - - - - -
PuntoDecision_MVPCero_min = 0
PuntoDecision_MVPCero_max = 2

# PuntoDecision_FactoresContexto (decisionContexto:PuntoDecision, factoresContexto:FactoresContexto)
PuntoDecision_FactoresContexto_min = 0
PuntoDecision_FactoresContexto_max = 2

# PuntoDecision_EquipoEmprendedor (decisionEquipo:PuntoDecision, equipoEmprendedor:EquipoEmprendedor)
PuntoDecision_EquipoEmprendedor_min = 0
PuntoDecision_EquipoEmprendedor_max = 2

# PuntoDecision_Restricciones (decisionRestriccion:PuntoDecision, restriccionRegulatoria:RestriccionRegulatoria)
PuntoDecision_Restricciones_min = 0
PuntoDecision_Restricciones_max = 2

# PuntoDecision_AuditoriaIA (decisionAuditoria:PuntoDecision, auditoriaIA:AuditoriaIA)
PuntoDecision_AuditoriaIA_min = 0
PuntoDecision_AuditoriaIA_max = 2

# PuntoDecision_EntornoLowCode (decisionEntorno:PuntoDecision, entornoLowCode:Entorno_LowCode)
PuntoDecision_EntornoLowCode_min = 0
PuntoDecision_EntornoLowCode_max = 2

# PuntoDecision_AgenteVibeCoding (decisionAgente:PuntoDecision, agenteVibeCoding:Agente_VibeCoding)
PuntoDecision_AgenteVibeCoding_min = 0
PuntoDecision_AgenteVibeCoding_max = 2

# PuntoDecision_Validacion (decisionValidacion:PuntoDecision, validaciones:Validacion)
PuntoDecision_Validacion_min = 0
PuntoDecision_Validacion_max = 2

# --------------------------------------------------------------------- MVP_Cero
MVP_Cero_min = 0
MVP_Cero_max = 2

MVP_Cero_costoEjecucion_min = 0
MVP_Cero_costoEjecucion_max = 1000
MVP_Cero_evidenciaTraccion_min = 0
MVP_Cero_evidenciaTraccion_max = 2

# MVPCero_CRL (mvpCero:MVP_Cero, crl:CRL)  - - - - - - - - - - - - - - - - - - -
MVPCero_CRL_min = 0
MVPCero_CRL_max = 2

# ------------------------------------------------------------- FactoresContexto
FactoresContexto_min = 0
FactoresContexto_max = 2

FactoresContexto_coherenciaPVBeneficiario_min = 0
FactoresContexto_coherenciaPVBeneficiario_max = 1
FactoresContexto_coherenciaPVProblema_min = 0
FactoresContexto_coherenciaPVProblema_max = 1
FactoresContexto_coherenciaPVSegmento_min = 0
FactoresContexto_coherenciaPVSegmento_max = 1
FactoresContexto_complejidadAlgoritmica_min = 0
FactoresContexto_complejidadAlgoritmica_max = 10
FactoresContexto_ejeImpactoPrincipal_min = 0
FactoresContexto_ejeImpactoPrincipal_max = 4
FactoresContexto_esTripleImpacto_min = 0
FactoresContexto_esTripleImpacto_max = 1
FactoresContexto_presupuestoDisponible_min = 0
FactoresContexto_presupuestoDisponible_max = 1000
FactoresContexto_propuestaValor_min = 0
FactoresContexto_propuestaValor_max = 2
FactoresContexto_requiereSoberaniaTotal_min = 0
FactoresContexto_requiereSoberaniaTotal_max = 1
FactoresContexto_tiempoLimite_min = 1
FactoresContexto_tiempoLimite_max = 10

# FactoresContexto_TeoriaCambio (contextoTeoria:FactoresContexto, teoriaCambio:TeoriaCambio)
FactoresContexto_TeoriaCambio_min = 0
FactoresContexto_TeoriaCambio_max = 2

# FactoresContexto_ODS (contextoODS:FactoresContexto, odsPrioritarios:ODS) - - -
FactoresContexto_ODS_min = 0
FactoresContexto_ODS_max = 2

# FactoresContexto_EquipoEmprendedor (contextoEquipo:FactoresContexto, equipoEmprendedor:EquipoEmprendedor)
FactoresContexto_EquipoEmprendedor_min = 0
FactoresContexto_EquipoEmprendedor_max = 2

# ----------------------------------------------------------------- TeoriaCambio
TeoriaCambio_min = 0
TeoriaCambio_max = 2

TeoriaCambio_poblacionObjetivo_min = 0
TeoriaCambio_poblacionObjetivo_max = 2
TeoriaCambio_problemaCentral_min = 0
TeoriaCambio_problemaCentral_max = 2

# ------------------------------------------------------------ EquipoEmprendedor
EquipoEmprendedor_min = 0
EquipoEmprendedor_max = 2

EquipoEmprendedor_nombreEquipo_min = 0
EquipoEmprendedor_nombreEquipo_max = 2
EquipoEmprendedor_puntajeCapacidades_min = 0
EquipoEmprendedor_puntajeCapacidades_max = 80
EquipoEmprendedor_titularidadPI_min = 0
EquipoEmprendedor_titularidadPI_max = 1

# EquipoEmprendedor_Miembros (equipoDeMiembro:EquipoEmprendedor, miembros:MiembroEquipo)
EquipoEmprendedor_Miembros_min = 1
EquipoEmprendedor_Miembros_max = 3

# ---------------------------------------------------------------- MiembroEquipo
MiembroEquipo_min = 0
MiembroEquipo_max = 3

MiembroEquipo_criterioTecnico_min = 1
MiembroEquipo_criterioTecnico_max = 10
MiembroEquipo_experienciaPrevia_min = 0
MiembroEquipo_experienciaPrevia_max = 10
MiembroEquipo_nombre_min = 0
MiembroEquipo_nombre_max = 2
MiembroEquipo_rol_min = 0
MiembroEquipo_rol_max = 2

# ------------------------------------------------------------------ Emprendedor
Emprendedor_min = 0
Emprendedor_max = 2

Emprendedor_perfil_min = 0
Emprendedor_perfil_max = 2

# Emprendedor_MVPCero (ejecutor:Emprendedor, mvpsEjecutados:MVP_Cero)  - - - - -
Emprendedor_MVPCero_min = 0
Emprendedor_MVPCero_max = 2

# ----------------------------------------------------------------- ProyectoEBCT
ProyectoEBCT_min = 0
ProyectoEBCT_max = 2

ProyectoEBCT_beneficiarioDeclarado_min = 0
ProyectoEBCT_beneficiarioDeclarado_max = 2
ProyectoEBCT_beneficiarioImpacto_min = 0
ProyectoEBCT_beneficiarioImpacto_max = 2
ProyectoEBCT_idProyecto_min = 0
ProyectoEBCT_idProyecto_max = 2
ProyectoEBCT_nombre_min = 0
ProyectoEBCT_nombre_max = 2
ProyectoEBCT_problemaCentral_min = 0
ProyectoEBCT_problemaCentral_max = 2
ProyectoEBCT_segmentoCliente_min = 0
ProyectoEBCT_segmentoCliente_max = 2
ProyectoEBCT_tipo_min = 0
ProyectoEBCT_tipo_max = 2

# ProyectoEBCT_EquipoEmprendedor (proyectoLiderado:ProyectoEBCT, equipoEmprendedor:EquipoEmprendedor)
ProyectoEBCT_EquipoEmprendedor_min = 1
ProyectoEBCT_EquipoEmprendedor_max = 2

# ProyectoEBCT_FactoresContexto (proyectoContextual:ProyectoEBCT, factoresContexto:FactoresContexto)
ProyectoEBCT_FactoresContexto_min = 1
ProyectoEBCT_FactoresContexto_max = 2

# ProyectoEBCT_PuntoDecision (proyectoGobernado:ProyectoEBCT, puntoDecision:PuntoDecision)
ProyectoEBCT_PuntoDecision_min = 1
ProyectoEBCT_PuntoDecision_max = 2

# ProyectoEBCT_MVPEspecializado (proyectoDesarrolla:ProyectoEBCT, mvpsDesarrollados:MVP_Especializado)
ProyectoEBCT_MVPEspecializado_min = 0
ProyectoEBCT_MVPEspecializado_max = 2

# ProyectoEBCT_Validacion (proyectoAcumula:ProyectoEBCT, acumulacionValidaciones:Validacion)
ProyectoEBCT_Validacion_min = 0
ProyectoEBCT_Validacion_max = 2

# --------------------------------------------------- EntornoDesarrolloAcelerado

EntornoDesarrolloAcelerado_active_min = 0
EntornoDesarrolloAcelerado_active_max = 2

# ------------------------------------------------------------ Agente_VibeCoding
Agente_VibeCoding_min = 0
Agente_VibeCoding_max = 2

Agente_VibeCoding_esProductoReal_min = 0
Agente_VibeCoding_esProductoReal_max = 1
Agente_VibeCoding_modeloIA_min = 0
Agente_VibeCoding_modeloIA_max = 2
Agente_VibeCoding_soberaniaCodigo_min = 0
Agente_VibeCoding_soberaniaCodigo_max = 1

# AgenteVibeCoding_CodigoFuenteReal (agenteGenerador:Agente_VibeCoding, codigoFuente:CodigoFuenteReal)
AgenteVibeCoding_CodigoFuenteReal_min = 1
AgenteVibeCoding_CodigoFuenteReal_max = 2

# AgenteVibeCoding_Script (agenteDeScript:Agente_VibeCoding, scriptsGenerados:Script)
AgenteVibeCoding_Script_min = 1
AgenteVibeCoding_Script_max = 2

# -------------------------------------------------------------- Entorno_LowCode
Entorno_LowCode_min = 0
Entorno_LowCode_max = 2

Entorno_LowCode_plataforma_min = 0
Entorno_LowCode_plataforma_max = 2

# ------------------------------------------------------------------ AuditoriaIA
AuditoriaIA_min = 0
AuditoriaIA_max = 2

AuditoriaIA_impactoEticoEvaluado_min = 0
AuditoriaIA_impactoEticoEvaluado_max = 1
AuditoriaIA_nivelAlineacionODS_min = 0
AuditoriaIA_nivelAlineacionODS_max = 10
AuditoriaIA_nivelExplicabilidad_min = 0
AuditoriaIA_nivelExplicabilidad_max = 10

# ------------------------------------------------------- RestriccionRegulatoria
RestriccionRegulatoria_min = 0
RestriccionRegulatoria_max = 2

RestriccionRegulatoria_cumplida_min = 0
RestriccionRegulatoria_cumplida_max = 1
RestriccionRegulatoria_idNormativa_min = 0
RestriccionRegulatoria_idNormativa_max = 2
RestriccionRegulatoria_impacto_min = 0
RestriccionRegulatoria_impacto_max = 2

# ------------------------------------------------------------------- Interesado
Interesado_min = 0
Interesado_max = 2

Interesado_nombre_min = 0
Interesado_nombre_max = 2
Interesado_rol_min = 0
Interesado_rol_max = 2

# ------------------------------------------------------------------- Validacion
Validacion_min = 0
Validacion_max = 2

Validacion_dimensionEvaluada_min = 0
Validacion_dimensionEvaluada_max = 2
Validacion_tipo_min = 0
Validacion_tipo_max = 2

# Validacion_Interesado (validacionDeInteresado:Validacion, interesado:Interesado)
Validacion_Interesado_min = 1
Validacion_Interesado_max = 2

# Validacion_MetricaClave (validacionDeMetrica:Validacion, metricaClave:MetricaClave)
Validacion_MetricaClave_min = 1
Validacion_MetricaClave_max = 2

# Validacion_MVPEspecializado (validacionDeMVP:Validacion, mvpValidado:MVP_Especializado)
Validacion_MVPEspecializado_min = 0
Validacion_MVPEspecializado_max = 2

# ----------------------------------------------------------------- MetricaClave
MetricaClave_min = 0
MetricaClave_max = 2

MetricaClave_nombre_min = 0
MetricaClave_nombre_max = 2
MetricaClave_valorObjetivo_min = 0
MetricaClave_valorObjetivo_max = 100
MetricaClave_valorObtenido_min = 0
MetricaClave_valorObtenido_max = 100

# -------------------------------------------------------------------------- ODS
ODS_min = 0
ODS_max = 2

ODS_id_min = 0
ODS_id_max = 16

# ------------------------------------------------------------ MVP_Especializado

MVP_Especializado_objetivo_min = 0
MVP_Especializado_objetivo_max = 2

# ------------------------------------------------------------------- MVPLowCode
MVPLowCode_min = 0
MVPLowCode_max = 2

MVPLowCode_plataforma_min = 0
MVPLowCode_plataforma_max = 2

# MVPLowCode_EntornoLowCode (mvpAcelerado:MVPLowCode, entornoAcelerador:Entorno_LowCode)
MVPLowCode_EntornoLowCode_min = 1
MVPLowCode_EntornoLowCode_max = 2

# ---------------------------------------------------------------- MVPVibeCoding
MVPVibeCoding_min = 0
MVPVibeCoding_max = 2

MVPVibeCoding_contextoImpacto_min = 0
MVPVibeCoding_contextoImpacto_max = 2
MVPVibeCoding_stackTecnico_min = 0
MVPVibeCoding_stackTecnico_max = 2

# MVPVibeCoding_AgenteVibeCoding (mvpGenerado:MVPVibeCoding, agenteDeMVP:Agente_VibeCoding)
MVPVibeCoding_AgenteVibeCoding_min = 1
MVPVibeCoding_AgenteVibeCoding_max = 2

# ------------------------------------------------------------- CodigoFuenteReal
CodigoFuenteReal_min = 0
CodigoFuenteReal_max = 2

CodigoFuenteReal_lenguaje_min = 0
CodigoFuenteReal_lenguaje_max = 2

# ----------------------------------------------------------------------- Script
Script_min = 0
Script_max = 2

Script_esPropiedadEBCT_min = 0
Script_esPropiedadEBCT_max = 1

# Script_CodigoFuenteReal (scriptMaterializado:Script, codigoFuenteDeScript:CodigoFuenteReal)
Script_CodigoFuenteReal_min = 1
Script_CodigoFuenteReal_max = 2
# ------------------------------------------------------------------------------
aggregationcyclefreeness = on
forbiddensharing = on

